# Generated by Django 3.0.6 on 2022-06-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrialgip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diariomp',
            old_name='producto',
            new_name='programado',
        ),
        migrations.RemoveField(
            model_name='diariomp',
            name='linea',
        ),
        migrations.AlterField(
            model_name='diariomp',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diariomp',
            name='inventariofinalkg',
            field=models.FloatField(default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='diariomp',
            name='observaciones',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Cordeleria'), ('2', 'Polybarq'), ('3', 'Andisacos')], default='2', max_length=50),
        ),
        migrations.AlterField(
            model_name='programado',
            name='estatus',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('TERM', 'Terminado')], default='PEND', editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='programado',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
