# Generated by Django 3.0.6 on 2022-07-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimoneda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasas',
            name='hora',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
