# Generated by Django 3.0.6 on 2022-07-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimoneda', '0002_auto_20220712_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasas',
            name='cambioabs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='cambio absoluto'),
        ),
        migrations.AlterField(
            model_name='tasas',
            name='cambiopor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='cambio porcentual'),
        ),
        migrations.AlterField(
            model_name='tasas',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasas',
            name='fuente',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tasas',
            name='item',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasas',
            name='medio',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tasas',
            name='mon_den',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='moneda denominador'),
        ),
        migrations.AlterField(
            model_name='tasas',
            name='mon_num',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='moneda numerador'),
        ),
        migrations.AlterField(
            model_name='tasas',
            name='tasa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tasas',
            name='textorg',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='texto original'),
        ),
    ]
